# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["jchampion@fastly.com"]
description = ""
language = "go"
manifest_version = 2
name = "object-store-go-starter-kit"
service_id = ""

[scripts]
  build = "tinygo build -target=wasi -gc=conservative -o bin/main.wasm ./"

[local_server]
[local_server.object_store]
[[local_server.object_store.my-store]]
  key = "readme"
  path = "./README.md"

[setup]
[setup.object_stores]
[setup.object_stores.my-store]
  description = "My first object store"